#------------------------------------------------
# NOTE: ECR Login is not included in the ansible-catapult-server role
# Get ECR login token. Run in Ansible host (localhost)
#------------------------------------------------
- name: Get AWS ECR login token - local_action
  become: false
  shell: "aws ecr get-login --no-include-email --region ap-southeast-1"
  delegate_to: 127.0.0.1
  run_once: true
  register: docker_login_cmd

#------------------------------------------------
# ECR Docker login
#------------------------------------------------
- name: Login to Docker ECR using temporary token
  shell: "{{ docker_login_cmd.stdout }}"

#------------------------------------------------
# Step 1: Create Catapult Server directories
#------------------------------------------------
- name: Create directory for catapult-server config resources
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    recurse: yes
    mode: 0744
  with_items:
  - "{{ catapult_config_directory }}/resources"
  - "{{ catapult_data_directory }}"

#------------------------------------------------
# Pull the Docker images from a Docker registry
#------------------------------------------------
- name: "Docker pull Catapult Server image"
  docker_image:
    name: "{{ catapult_server_repository_name }}"
    tag: "{{ catapult_server_docker_tag }}"

- name: "Docker pull Catapult REST image"
  docker_image:
    name: "{{ catapult_rest_repository_name }}"
    tag: "{{ catapult_rest_docker_tag }}"

#------------------------------------------------
# Create scripts and configuration files from populated Jinja2 templates
#------------------------------------------------
- name: Generate Catapult Server Configuration Files
  template:
    src: "{{ item }}.j2"
    dest: "{{ catapult_config_directory }}/resources/{{ item }}"
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    mode: u+r
  with_items:
  - config-database.properties
  - config-harvesting.properties
  - config-logging.properties
  - config-messaging.properties
  - config-network.properties
  - config-networkheight.properties
  - config-node.properties
  - config-pt.properties
  - config-task.properties
  - config-timesync.properties
  - config-user.properties
  - peers-api.json
  - peers-p2p.json

#------------------------------------------------
# If running Catapult-Server PEER Mode
#------------------------------------------------
- name: Docker compose file for running Catapult Server container
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ catapult_config_directory }}/docker-compose.yml"
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    mode: u+r
  when: node_config['localnode_roles'] is not defined or node_config['localnode_roles'] != "Api"

#------------------------------------------------
# If running Catapult-Server API Mode
#------------------------------------------------
- name: Catapult API Node - create directory for catapult-server API Node
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    recurse: yes
    mode: 0744
  with_items:
  - "{{ catapult_rest_user_config }}"
  - "{{ mongodb_data_directory }}"
  - "{{ catapult_scripts_directory }}"
  - "{{ catapult_scripts_directory }}/mongo"
  when: node_config['localnode_roles'] is defined and node_config['localnode_roles'] == "Api"

- name: Catapult API Node - copy the mongodb scripts
  copy:
    src: "{{ item }}"
    dest: "{{ catapult_scripts_directory }}/{{ item }}"
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    mode: 0644
  with_items:
  - "mongo/mongors.sh"
  - "mongo/mongoNamespaceDbPrepare.js"
  - "mongo/mongoMultisigDbPrepare.js"
  - "mongo/mongoDbPrepare.js"
  - "mongo/mongoDbDrop.js"
  - "mongo/mongoReputationDbPrepare.js"
  - "mongo/mongoContractDbPrepare.js"
  - "mongo/mongoLockInfoDbPrepare.js"
  - "mongo/mongoAccountPropertiesDbPrepare.js"

  when: node_config['localnode_roles'] is defined and node_config['localnode_roles'] == "Api"

- name: Catapult API Node - Docker compose file for Catapult Server API Node
  template:
    src: "docker-compose-api-node.yml.j2"
    dest: "{{ catapult_config_directory }}/docker-compose.yml"
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    mode: u+r
  when: node_config['localnode_roles'] is defined and node_config['localnode_roles'] == "Api"

- name: Catapult API Node - generate Catapult REST JSON configuration file
  template:
    src: "{{ item }}.j2"
    dest: "{{ catapult_rest_user_config }}/{{ item }}"
    owner: "{{ catapult_user }}"
    group: "{{ catapult_group }}"
    mode: u+r
  with_items:
  - rest.json
  when: node_config['localnode_roles'] is defined and node_config['localnode_roles'] == "Api"
